config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  get 'index'  => 'home#index'
  get 'settings'  => 'home#settings'

  
  get 'pending'  => 'home#pending'
  get 'show' => 'home#show'
  get 'resumen' => 'home#resumen'

  get 'products' => 'product#index'

  root 'home#index'

end

app/models/session_storage.rb
class SessionStorage
  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShopifyApp::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout ShopifyApp.configuration.embedded_app? ? 'embedded_app' : 'application'
end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  
  def index
    @pufipad = ShopifyAPI::Shop.current
  end

  def settings
    
  end

  def pending
  	@orders = ShopifyAPI::Order.find(:all, :params => {:fields => "id,name,created_at,email,financial_status,total_price", :financial_status => "pending", :limit => 250})
  end

  def show
  	@orders = ShopifyAPI::Order.find(:all, :params => {:fields => "id,name,created_at,email,financial_status,total_price", :name => params[:name], :limit => 1 })
  	render action: 'index'
  end

  def resumen
    @orders = ShopifyAPI::Order.find(:all, :params => {:name => params[:name], :limit => 1 })
  end

end

app/controllers/product_controller.rb
class ProductController < AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all)    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ShopifyApp::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/home/edit.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      buttons: {
        primary: {
          label: 'Print',
          print: true
        }
      },
  buttons: {
    primary: {
      label: "Refresh",
      message: 'bar_save',
      loading: false
    },
    secondary: [
      { label: "Help", callback: function(){ alert('help'); } },
      { label: "Configuration", href: "http://my-app.com/preview_url", target: "new" }
    ],
  },
  title: 'Call Phone Orders',
  icon: 'https://example.com/path/to/icon.png',
  pagination: {
    next: {
      href: "/posts?page=2"
    },
    previous: {
      callback: function(){ alert('no previous pages') },
      loading: false
    }
  }
});
  });
</script>
<div class="section-listing">
    <div class="section-options">
        <ul class="section-tabs">
            <li class="active"><%= link_to "All", index_path %></li>
            <li class="active"><%= link_to "Pending", pending_path %></li>
            
        </ul>
        <div class="section-filter">
          <div class="section-row">
            <%= form_tag(show_path, method: "get") do %>
              <%= label_tag(:name , "Buscar por:") %>
              <%= text_field_tag(:name) %>
              <%= submit_tag("Buscar, ej. #1001") %>  
            <% end %>
          </div>
        </div>
        <div class="section-content">
            <div class="section-row">  
              <%= form_for url: edit_path, method: :post do |f| %>
                  <%= f.text_field(:name) %>
                  <%= f.text_field(:email) %>
                  <%= f.submit %>  
              <% end %>
            </div>
        </div>
    </div>
</div>        

app/views/home/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: 'Home',
      icon: 'shopify.png',      
      buttons: {
        secondary: [
          {
            label: "Configuracion",
            href: "/settings",
            target: 'app'
          },
          {
            label: "Ordenes Pendientes",
            href: "/pending",
            target: 'app'
          }
        ]
      }      
    });
  });
</script>
<div class="section">
    <div class="section-content">
        <div class="section-row">
            <div class="section-cell">
                <h1>Shop: <%= @pufipad.domain %></h1>
            </div>
        </div>
    </div>
</div>

app/views/home/pendientes.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      buttons: {
        primary: {
          label: 'Print',
          print: true
        }
      },
  buttons: {
    primary: {
      label: "Refresh",
      message: 'bar_save',
      loading: false
    },
    secondary: [
      { label: "Help", callback: function(){ alert('help'); } },
      { label: "Configuration", href: "http://my-app.com/preview_url", target: "new" }
    ],
  },
  title: 'Call Phone Orders',
  icon: 'https://example.com/path/to/icon.png',
  pagination: {
    next: {
      href: "/posts?page=2"
    },
    previous: {
      callback: function(){ alert('no previous pages') },
      loading: false
    }
  }
});
  });
</script>
<div class="section-listing">
    <div class="section-options">
        <ul class="section-tabs">
            <li class="active"><%= link_to "All", home_index_url %></li>
            <li class="active"><%= link_to "Pendientes", home_pendientes_url %></li>
            
        </ul>
        <div class="section-filter">
          <div class="section-row">
            <input class="input-search" placeholder="Order number..." type="text">
          </div>
        </div>
        <div class="section-content">
            <div class="section-row">
                <table class="table-section">
                  <thead>
                  <tr>
                      <th class="sortable">Order #</th>
                      <th class="sortable">Date</th>
                      <th class="sortable">Email</th>
                      <th class="sortable">Payment Status</th>
                      <th class="sortable">Total</th>
                      <th></th>
                  </tr>
                  </thead>
                  <tbody>
                      <% @orders.each do |order| %>
                        <tr>
                          <td><%= order.name %> </a></td>
                          <td><%= order.created_at %></td>
                          <td><%= order.email %></td>
                          <td><%= order.financial_status %></td>
                          <td><%= order.total_price %></td>
                          <td><a href="#top" class="btn default">Cobrar</a></td>
                        </tr>
                      <% end %>
                  </tbody>
                </table>
            </div>
        </div>
    </div>
</div>        

app/views/home/settings.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: 'Configuracion de Paypal PLUS',
      icon: 'shopify.png',
      buttons: {
        primary: {
          label: "Guardar configuracion",
          message: ''
        },
        secondary: 
          {
            label: "Ordenes Pendientes",
            href: "/pending",
            target: 'app'
          }
      }      
    });
  });
</script>


<div class="section">
    
    <div class="section-content">
        <div class="section-row">
            <div class="section-cell">
                <h1>Beneficios</h1>

                Paypal PLUS permite aceptar cargos con tarjeta de crédito y débito SIN que tu cliente tenga una cuenta de Paypal.<b>
                Tarjetas y bancos aceptados ???<br>
                Acepta MSI(configuración desde tu cuenta de Paypal de empresa)
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="section-summary">
        <h1>Requisitos</h1>
        <p>Requisitos</p>
    </div>
    <div class="section-content">
        <div class="section-row">
            <div class="section-cell">
                Para usar Paypal PLUS es necesario:
                <ul>
                  <li>Tener una cuenta de PayPal ¿México?</li>
                  <li>Qye Paypal te apruebe la cuenta</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="section-summary">
        <h1>Client ID + Secret</h1>
        <small>
          <p>Generador de credenciales para pasarela de pagos PayPal<br>
             Se requiere tu Client ID + Secret, los puede obtener en <a href="#">Developer Paypal</a>
          </p>
        </small>
    </div>
    <div class="section-content">
        <div class="section-row">
            <div class="section-cell">
              <form>
                Cliente ID <input type="text" name="" placeholder="Copia y Pega el CLIENT ID de tu cuenta de Developer de Paypal">
                Secret <input type="text" name="" placeholder="Copia y Pega el SECRET de tu cuenta de Developer de Paypal">
                Nombre de perfil <input type="text" name="" placeholder="Introduce un nombre para identificar esta instalación">
                Nombre de Comercio <input type="text" name="" placeholder="{{shop.name}}">
                Pasarela de pago <select>
                <option>Opcion 1</option>
                <option>Opcion 2</option>
                <option>Opcion 3</option>
                </select>

              </form>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp01</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Embedded Example App</title>

  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "<%= ShopifyApp.configuration.api_key %>",
      shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
      debug: <%= Rails.env.development? ? 'true' : 'false' %>
    });
  </script>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/product/index.html.erb
<% @products.each do |p| %>
ID: <%= p.id %><br>
Titulo: <%= p.title %><br>
Variants: <br>

	<% p.variants.each do |variant| %>
		Variant Title: <%= variant.title %>
		Variant Price: <%= variant.price %>
	<% end %>

<hr>
<% end %>